In [298]:
#Author: Jephter Danso Kumuyi on 27th Dec, 2018

# import my libraries or packages
import numpy as np
import matplotlib as mp


# declare my constant variables
boldAnswer = "\033[1m"
unboldString = "\033[0m"


In [295]:
#Question 1a

A = np.array([[4,0,1], 
             [0,1,0],
             [4,0,1]])

x = np.array([[3], [4],[5]])

B = np.matmul(A,x)
print("{}Answer for 1a is : \n{}{}".format(unboldString,boldAnswer,B))

#Question 1b

A = np.array([[1,0,0], 
             [0,1,0],
             [0,0,1]])

x = np.array([[5], [-2],[3]])

B = np.matmul(A,x)

print("\n{}Answer for 1b is :\n {}{}".format(unboldString,boldAnswer,B))

#Question 1c

A = np.array([[2,0], 
             [1,3]])

x = np.array([[1],[1]])

B = np.matmul(A,x)

print("\n{}Answer for 1c is : \n{}{}{}".format(unboldString,boldAnswer,B,unboldString))


#Question 1d

print("\nQuestion 1d: Please I don't know how to represent it graphically")

Answer for 1a is : 
[[17]
 [ 4]
 [17]]

Answer for 1b is :
 [[ 5]
 [-2]
 [ 3]]

Answer for 1c is : 
[[2]
 [4]]

Question 1d: Please I don't know how to represent it graphically


In [136]:
#Question 2a

A1 = (np.array([[4], 
             [5],
             [6]]))*1


A2 = (np.array([[1], 
             [1],
             [1]]))*3

A = A1 + A2
print("{}Answer for 2a is : \n{}{}".format(unboldString,boldAnswer,A))


# Question 2b

A1 = (np.array([[1], 
             [4],
             [7]]))*0


A2 = (np.array([[2], 
             [5],
             [8]]))*1

A3 = (np.array([[3], 
             [6],
             [9]]))*0

A = A1 + A2 + A3
print("\n{}Answer for 2b is : \n{}{}".format(unboldString,boldAnswer,A))

#Question 2c

A1 = (np.array([[4], 
             [6],
             [8]]))*(1/2)


A2 = (np.array([[3], 
             [6],
             [9]]))*(1/3)

A = A1 + A2
print("\n{}Answer for 2c is : \n{}{}".format(unboldString,boldAnswer,A))


Answer for 2a is : 
[[7]
 [8]
 [9]]

Answer for 2b is : 
[[2]
 [5]
 [8]]

Answer for 2c is : 
[[3.]
 [5.]
 [7.]]


In [105]:
# Question 3a

A = np.array([[1,-2,7]])


x = np.array([[1], 
             [-2],
             [7]])

B = np.matmul(A,x)
print("{}Answer for 3a is : \n{}{}".format(unboldString,boldAnswer,B))


# Question 3b

A = np.array([[1,-2,7]])


x = np.array([[3], 
             [5],
             [1]])

B = np.matmul(A,x)
print("\n{}Answer for 3b is : \n{}{}".format(unboldString,boldAnswer,B))


# Question 3c

A1 = np.array([[1], 
             [-2],
             [7]])

A2 = np.array([[3,5,1]])


A = np.matmul(A1,A2)
print("\n{}Answer for 3c is : \n{}{}".format(unboldString,boldAnswer,A))



Answer for 3a is : 
[[54]]

Answer for 3b is : 
[[0]]

Answer for 3c is : 
[[  3   5   1]
 [ -6 -10  -2]
 [ 21  35   7]]


In [294]:
#Question 4 a & b

print("Do not  know how to represent sigma notation")

Do not  know how to represent sigma notation


In [158]:
# Question 5a

A = np.array([[3,-6,0], 
             [0,2,-2],
             [1,-1,-1]])

x = np.array([[2], [1],[1]])

B = np.matmul(A,x)
print("{}Answer for 5a is : \n{}{}\n\n{}Hence;\n x={}{}{} is a solution".format(unboldString,boldAnswer,B,unboldString,boldAnswer,x,unboldString))



# Question 5b

print("\nQuestion 1d: Please I don't know how to represent it graphically")

Answer for 5a is : 
[[0]
 [0]
 [0]]

Hence;
 x=[[2]
 [1]
 [1]] is a solution


In [256]:
# Question 6a

print('A = \t[[1+1,1+2],\n\t[2+1,2+2]] = \n\t{}[[2,3],\n\t[3,4]]{}'.format(boldAnswer,unboldString))

# Question 6b

print('\nB = \t[[(-1)\u00b9+\u00b9, (-1)\u00b9+\u00b2], = \n\t[(-1)\u00b2+\u00b9, (-1)\u00b2+\u00b2]]\n\t{}[[1,-1],\n\t[-1,1]]{}'.format(boldAnswer,unboldString))
      

A = np.array([[1+1,1+2],[2+1,2+2]])
B = np.array([[1,-1],[-1,1]])

# Question 6c

C = np.matmul(A,B)
print("{}AB : \n{}{}\n\n{}".format(unboldString,boldAnswer,C,unboldString,unboldString))

# Question 6d

D = np.matmul(B,A)
print("{}BA : \n{}{}\n\n{}".format(unboldString,boldAnswer,D,unboldString,unboldString))





A = 	[[1+1,1+2],
	[2+1,2+2]] = 
	[[2,3],
	[3,4]]

B = 	[[(-1)¹+¹, (-1)¹+²], = 
	[(-1)²+¹, (-1)²+²]]
	[[1,-1],
	[-1,1]]
AB : 
[[-1  1]
 [-1  1]]


BA : 
[[-1 -1]
 [ 1  1]]




In [264]:
# Question 7a

D = np.array([[4,0,0], 
             [0,1,0],
             [0,0,10]])
print("{}Diagonal Matrix(D) = \n{}{}\n\n{}".format(unboldString,boldAnswer,D,unboldString,unboldString))

      
#Question 7b

S = np.array([[1,2,3], 
             [2,5,8],
             [3,8,9]])
print("{}Symmetric Matrix(S) = \n{}{}\n\n{}".format(unboldString,boldAnswer,S,unboldString,unboldString))

      
#Question 7c

U = np.array([[12,3,-1], 
             [0,5,7],
             [0,0,6]])
print("{}Upper Triangular Matrix(U) = \n{}{}\n\n{}".format(unboldString,boldAnswer,U,unboldString,unboldString))

      
#Question 7d

W = np.array([[0,3,-1], 
             [-3,0,7],
             [1,-7,0]])
print("{}Skew-symmetric Matrix(W) = \n{}{}\n\n{}".format(unboldString,boldAnswer,W,unboldString,unboldString))

          
      
      
      

Diagonal Matrix(D) = 
[[ 4  0  0]
 [ 0  1  0]
 [ 0  0 10]]


Symmetric Matrix(S) = 
[[1 2 3]
 [2 5 8]
 [3 8 9]]


Upper Triangular Matrix(U) = 
[[12  3 -1]
 [ 0  5  7]
 [ 0  0  6]]


Skew-symmetric Matrix(W) = 
[[ 0  3 -1]
 [-3  0  7]
 [ 1 -7  0]]


